export const POST_LIVESTREAM = "POST_LIVESTREAM";
export const FETCH_ALL_LIVESTREAMS = "FETCH_ALL_LIVESTREAMS";
export const SET_CURRENT_LIVESTREAM = "SET_CURRENT_LIVESTREAM";
export const SET_IS_STREAMER = "SET_IS_STREAMER";
export const SET_PARTICIPANTS = "SET_PARTICIPANTS";